services:
  # Jenkins : L'automate qui va gérer le build et le déploiement
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080" # Interface Web
      - "50000:50000" # Communication agents
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Permet à Jenkins d'utiliser Docker
    networks:
      - internal

  # SonarQube : L'analyseur de qualité de code
  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    networks:
      - internal

  # Nexus : Le dépôt pour stocker vos fichiers JAR
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    networks:
      - internal

networks:
  internal:

volumes:
  jenkins_data: